### ISSUE TITLE
Add support for more event types

### ISSUE THREAD

**Issue by robinjmurphy** [robinjmurphy/hubot-npm#1]
Take inspiration from https://github.com/npm/npm-hook-slack/blob/master/index.js#L41-L81

**Comment by soldair** [comment]
this is the full documentation on the payload format and events https://github.com/npm/registry/blob/master/docs/hooks/hooks-payload.md

just in case it helps :smile: 

this is very cool!

**Comment by robinjmurphy** [comment]
Thanks @soldair this will help with tests 👍

**Comment by robinjmurphy** [comment]
* [ ] package:star
* [ ] package:unstar
* [x] package:publish
* [x] package:unpublish
* [ ] package:owner
* [ ] package:owner-rm
* [ ] package:dist-tag
* [ ] package:dist-tag-rm
* [ ] package:deprecate
* [ ] package:undeprecate
* [ ] package:change

**Comment by robinjmurphy** [comment]
@soldair I'm getting `package:change` when I add/remove an owner instead of `package:owner` and `package:owner-rm`. Not sure if that's to be expected?

I'm using `npm owner add ...` and `npm owner rm ...`.

**Comment by soldair** [comment]
I'll check it out :) thanks for the report!

**Comment by robinjmurphy** [comment]
Just raised https://github.com/npm/registry/pull/24 too. Not sure if it's the docs or the hooks that aren't quite right.

**Comment by soldair** [comment]
so i want to see if you hit this implementation detail.

if you owner add owner rm the same package do you still get package:change?

the first hook event i process for any package is always `package:change` because i dont have a previous copy of the document to compare it against in the cache.

**Comment by soldair** [comment]
i have a plan to fix this though =). its just that package:change is the default when i can't figure out what happened.

this also effects the first publish ever of a new module. im going to look in the object and if its only ever had one release force the event type to `package:publish` which should fix this oddity

**Comment by robinjmurphy** [comment]
```bash
❯ npm owner add soldair               
+ soldair (npm-hook-test)
```

```bash
2016-06-02T14:31:48.619Z package:change
```

```bash
❯ npm owner add soldair
```

```bash
# no change so no hook
```

```bash
❯ npm owner rm soldair 
- soldair (npm-hook-test)
```

```bash
2016-06-02T14:32:11.942Z package:change
```

```bash
❯ npm owner rm soldair 
```

```bash
# no change so no hook
```

**Comment by robinjmurphy** [comment]
Yeah I spotted the first ever publish coming through as a change too. Subsequent publishes worked fine.

**Comment by soldair** [comment]
ok ill hit this owner issue and add a test now

**Comment by soldair** [comment]
fixed and deployed!
a test is in place to to protect it. thank you so much for finding it

**Comment by robinjmurphy** [comment]
Thanks for the quick fix. Add/remove working perfectly for me now.
