### ISSUE TITLE
Actually use secret to verify request

### ISSUE THREAD

**Issue by robinjmurphy** [robinjmurphy/hubot-npm#2]
See https://github.com/npm/npm-hook-receiver/blob/master/index.js#L16-L30

**Comment by soldair** [comment]
working on this? i :clap: when i saw the status change from 400 to  `"package":"npm-hook-test","type":"publish","statusCode":200}`

**Comment by robinjmurphy** [comment]
Not quite 😃  Just some logging around the `?room` parameter but I want to pick this one up next.
